# CI for automated build and publish of project Docker containers

stages:
  - build
  - build_push

variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:${CI_COMMIT_TAG}
    IMAGE_TEST_BUILD: $CI_REGISTRY_IMAGE:test-build

# Check only for successful Docker image build
docker_build:
    stage: build
    before_script: [ ] # Prevent global before_script from running
    image:
        name: gcr.io/kaniko-project/executor:v1.23.2-debug
        entrypoint: [""]
    script:
        - /kaniko/executor
            --context "${CI_PROJECT_DIR}"
            --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
            --destination "${IMAGE_TEST_BUILD}"
            --no-push
    except:
        - tags

# Build and publish Docker image when a new tag is defined
docker_build_push:
    stage: build_push
    image:
        name: gcr.io/kaniko-project/executor:v1.23.2-debug
        entrypoint: [""]
    before_script:
        - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"username\":\"${CI_REGISTRY_USER}\",\"password\":\"${CI_REGISTRY_PASSWORD}\"}}}" > /kaniko/.docker/config.json
    script:
        - /kaniko/executor
            --context "${CI_PROJECT_DIR}"
            --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
            --destination "${IMAGE_TAG}"
    only:
        - tags
    except:
        - branches
